//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIDAW.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewDocTypeWorkGroup
    {
        public int Id { get; set; }
        public string NameTH { get; set; }
        public string NameEN { get; set; }
        public Nullable<int> WorkflowGroupId { get; set; }
        public string NameTH_wfg { get; set; }
        public string NameEN_wfg { get; set; }
    }
}
