//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIDAW.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewUserDpm
    {
        public int Id { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public string NameTH { get; set; }
        public string LastNameTH { get; set; }
        public string NameEN { get; set; }
        public string LastNameEN { get; set; }
        public string Email { get; set; }
        public string PhoneNumber { get; set; }
        public Nullable<bool> IsLeader { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public int Id_Dpm { get; set; }
        public string NameTH_Dpm { get; set; }
        public string NameEN_Dpm { get; set; }
    }
}
