//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIDAW.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Workflow
    {
        public int Id { get; set; }
        public Nullable<int> WorkflowGroupId { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public Nullable<int> SEQ { get; set; }
        public Nullable<int> StatusBefoerId { get; set; }
        public Nullable<int> StatusAfterId { get; set; }
        public Nullable<int> ActionId { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual WorkflowGroup WorkflowGroup { get; set; }
        public virtual Actions Actions { get; set; }
    }
}
